language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
      - LARAVEL=^6.0  TESTBENCH=4.7.* PHPUNIT=8.4.*
      - LARAVEL=^7.0  TESTBENCH=5.1.* PHPUNIT=8.4.*

      # All versions below only support PHP ^7.3 (Laravel requirement)
      - LARAVEL=^8.0  TESTBENCH=^6.0 PHPUNIT=9.3.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
